drop table if exists course;

create table course (
                        id bigint generated by default as identity,
                        begin_date date,
                        description varchar(1000) not null,
                        end_date date,
                        price double not null,
                        state varchar(255),
                        title varchar(20) not null,
                        primary key (id)
);

